In [5]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from word2number import w2n

In [7]:
d = pd.read_csv("salary_predict_dataset.csv")
d

   experience  test_score  interview_score  Salary
0         NaN         8.0              8.0   50000
1         NaN         5.0              4.0   22000
2       three         6.0              5.0   30000
3        five         9.0              9.0   55000
4         six         3.0              5.0   13000
5         NaN         2.0              1.0    9000
6         ten         8.0              6.0   48000
7         one         1.0              2.0     500
8     fifteen         9.0              9.0   60000
9    thirteen         7.5              7.5   45000
10        ten         NaN              5.0   25000
11        NaN         1.0              1.0     500
12        one         3.0              6.0   25000
13       four         5.0              4.0   36000
14        six         5.0              NaN    8000
15     eleven         9.0              8.0   55000
16     twelve         9.0              9.0   58000
17        NaN         2.0              6.0   12000
18      three         5.0              5.0   20000
19       five         6.0              7.0   35000

In [8]:
d.experience = d.experience.fillna("zero")
d

   experience  test_score  interview_score  Salary
0        zero         8.0              8.0   50000
1        zero         5.0              4.0   22000
2       three         6.0              5.0   30000
3        five         9.0              9.0   55000
4         six         3.0              5.0   13000
5        zero         2.0              1.0    9000
6         ten         8.0              6.0   48000
7         one         1.0              2.0     500
8     fifteen         9.0              9.0   60000
9    thirteen         7.5              7.5   45000
10        ten         NaN              5.0   25000
11       zero         1.0              1.0     500
12        one         3.0              6.0   25000
13       four         5.0              4.0   36000
14        six         5.0              NaN    8000
15     eleven         9.0              8.0   55000
16     twelve         9.0              9.0   58000
17       zero         2.0              6.0   12000
18      three         5.0              5.0   20000
19       five         6.0              7.0   35000

In [9]:
d.experience = d.experience.apply(w2n.word_to_num)
d

    experience  test_score  interview_score  Salary
0            0         8.0              8.0   50000
1            0         5.0              4.0   22000
2            3         6.0              5.0   30000
3            5         9.0              9.0   55000
4            6         3.0              5.0   13000
5            0         2.0              1.0    9000
6           10         8.0              6.0   48000
7            1         1.0              2.0     500
8           15         9.0              9.0   60000
9           13         7.5              7.5   45000
10          10         NaN              5.0   25000
11           0         1.0              1.0     500
12           1         3.0              6.0   25000
13           4         5.0              4.0   36000
14           6         5.0              NaN    8000
15          11         9.0              8.0   55000
16          12         9.0              9.0   58000
17           0         2.0              6.0   12000
18           3         5.0              5.0   20000
19           5         6.0              7.0   35000

In [10]:
import math
median_test_score = math.floor(d['test_score'].mean())
median_test_score

5

In [11]:
d['test_score'] = d['test_score'].fillna(median_test_score)
d

    experience  test_score  interview_score  Salary
0            0         8.0              8.0   50000
1            0         5.0              4.0   22000
2            3         6.0              5.0   30000
3            5         9.0              9.0   55000
4            6         3.0              5.0   13000
5            0         2.0              1.0    9000
6           10         8.0              6.0   48000
7            1         1.0              2.0     500
8           15         9.0              9.0   60000
9           13         7.5              7.5   45000
10          10         5.0              5.0   25000
11           0         1.0              1.0     500
12           1         3.0              6.0   25000
13           4         5.0              4.0   36000
14           6         5.0              NaN    8000
15          11         9.0              8.0   55000
16          12         9.0              9.0   58000
17           0         2.0              6.0   12000
18           3         5.0              5.0   20000
19           5         6.0              7.0   35000